sudo: false
language: php
php:
  - '5.6'
service:
    - mongodb
before_script:
    - export TZ='UTC'
    - composer self-update
    - composer update
    - phpenv config-add mongoconfig.ini
script:
  ./vendor/bin/phpunit --testsuite UnitTest
